spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://101.37.83.15:49700/basic?serverTimezone=Asia/Shanghai
    username: basic
    password: Basic$0827.&